module.exports = { up: queryInterface => queryInterface.bulkInsert('Permissions', [{ role: 'superAdmin',
  actions: 'GET',
  tablesAllowed: ['Articles', 'Blacklist', 'Bookmarks', 'comments', 'Follow', 'LikeAndDislike', 'notification', 'opts', 'Permissions', 'Ratings', 'User'] },
{ role: 'superAdmin',
  actions: 'POST',
  tablesAllowed: ['Articles', 'Blacklist', 'Bookmarks', 'comments', 'Follow', 'LikeAndDislike', 'notification', 'opts', 'Permissions', 'Ratings', 'User'] },
{ role: 'superAdmin',
  actions: 'DELETE',
  tablesAllowed: ['Articles', 'Blacklist', 'Bookmarks', 'comments', 'Follow', 'LikeAndDislike', 'notification', 'opts', 'Permissions', 'Ratings', 'User'] },
{ role: 'superAdmin',
  actions: 'PUT',
  tablesAllowed: ['Articles', 'Blacklist', 'Bookmarks', 'comments', 'Follow', 'LikeAndDislike', 'notification', 'opts', 'Permissions', 'Ratings', 'User'] },
{ role: 'superAdmin',
  actions: 'PATCH',
  tablesAllowed: ['Articles', 'Blacklist', 'Bookmarks', 'comments', 'Follow', 'LikeAndDislike', 'notification', 'opts', 'Permissions', 'Ratings', 'User'] },
{ role: 'normalUser',
  actions: 'GET',
  tablesAllowed: ['Articles', 'Bookmarks', 'comments', 'Follow', 'LikeAndDislike', 'notification', 'opts', 'Ratings', 'User'] },
{ role: 'normalUser',
  actions: 'POST',
  tablesAllowed: ['Articles', 'Bookmarks', 'comments', 'Follow', 'LikeAndDislike', 'notification', 'opts', 'Ratings', 'User'] },
{ role: 'normalUser',
  actions: 'DELETE',
  tablesAllowed: ['Articles', 'Bookmarks', 'comments', 'Follow', 'notification', 'opts'] },
{ role: 'normalUser',
  actions: 'PUT',
  tablesAllowed: ['Articles', 'Bookmarks', 'comments', 'Follow', 'notification', 'opts'] },
{ role: 'normalUser',
  actions: 'PATCH',
  tablesAllowed: ['Articles', 'Bookmarks', 'comments', 'Follow', 'notification', 'opts'] },
], {}),

down: queryInterface => queryInterface.bulkDELETE('User', null, {}) };
